#!/usr/bin/env bash

function editor() {
	[ "$EDITOR" != "" ] && echo $EDITOR && return
	which vi && return
	which nano && return
	which ed
}

function download() {
	if [ "$1" != "" ]
	then
		ENVS=$1
	fi
	if [ "$COPY_ENV" == "1" ]
	then
		TEMPFILE=$(mktemp)
		echo "# Check env variables bellow from tsuru to be copied to local" > $TEMPFILE
		echo "" >> $TEMPFILE
		tsuru app-run -o "env|sed \"s/\(^[^=]*=\)\(.*\)/export \1'\2'/\"" -a $APP >> $TEMPFILE
		$(editor) $TEMPFILE
		ENVS=$(cat $TEMPFILE)
	fi
	echo "Wait while copying unit. It may take several minutes..." 
	if ! tsuru app-run -oi "echo \"$ENVS\" > /home/ubuntu/.envs; sudo tar -czf - 2>/dev/null / | base64" -a $APP | base64 --decode | docker import - $DOCKER_IMG
	then
		echo "Error while downloading!"
		exit 1
	fi
	echo "Download done!"
}

function get_start_script() {
	docker run -it --rm $DOCKER_IMG sed "s/^[^:]*: *//" /home/application/current/Procfile | tr -d "\r" | head -n1
}

function get_docker_envs() {
	docker run -it --rm $DOCKER_IMG cat /home/ubuntu/.envs | tr -d "\r" 
}

function start(){
	if [ -z "$(docker images $DOCKER_IMG -q)" ] 
	then
		echo "Downloading image..."
		download "$1"
	fi
	[ "$FOLDER" != "" ] && FOLDER_CMD="-v $FOLDER:/home/application/current"
	eval docker run -it --rm $FOLDER_CMD -e PORT=8888 -e port=8888 -u ubuntu -w /home/application/current -p $PORT:8888 $DOCKER_IMG /bin/bash -lc  \"tail -f /dev/null \& source /home/ubuntu/.envs \&\& $(get_start_script)\"
}

function update() {
	ENVS=$(get_docker_envs)
	delete && start "$ENVS"
}

function delete() {
	if [ -z "$(docker images $DOCKER_IMG -q)" ]
	then
		echo "Image not found"
	else
		docker rmi $DOCKER_IMG:latest --force
	fi
}

function main() {
	case "$1" in
	   update)
		  update
		  ;;
	   start)
		  start
		  ;;
	   delete)
		  delete
		  ;;
	esac
}

function help() {
	echo "Usage: tsuru $(basename $0) -a|--app <appname> [-p|--process <processname>] [-l|--local-folder <folderpath>] [-c|--copy-environment] [-P|--port <port|8888>]  [update | start | delete]"
}

unset FOLDER_CMD
unset FOLDER
unset ENVS
unset APP
unset DOCKER_IMG
export COPY_ENV=0
export PORT=8888
while [[ $# -ge 1 ]]
do
	key="$1"
	case $key in
		""|--help|-h)
			help
			exit 0
		;;
		-a|--app)
			export APP="$2"
			export DOCKER_IMG="$APP-tsuru"
			shift # past argument
		;;
		-p|--process)
			export PROCESSNAME="$2"
			shift # past argument
		;;
		-P|--port)
			export PORT="$2"
			shift # past argument
		;;
		-c|--copy-environment)
			export COPY_ENV=1
		;;
		-l|--local-folder)
			export FOLDER="$(cd $2; pwd)"
			shift # past argument
		;;
		update|start|delete)
			MODE="$1" 
		;;
		*)
			help
			exit 1
		;;
	esac
	shift # past argument or value
done

if ! which docker > /dev/null
then
	echo "Please install docker"
	exit 1
fi

if [ "$APP" == "" ] || [ "$MODE" == "" ]
then
	help
	exit 1
fi

main "$MODE"
