#!/usr/bin/env bash

function download() {

	echo "Wait while copying unit..." 
	ENVS=$(tsuru app-run -o "env|sed \"s/\(^[^=]*=\)\(.*\)/export \1'\2'/\"" -a $APP)
	if ! tsuru app-run -oi "echo \"$ENVS\" > /home/ubuntu/.envs; sudo tar -czf - 2>/dev/null / | base64" -a $APP | base64 --decode | docker import - $DOCKER_IMG
	then
		echo "Error while downloading!"
		exit 1
	fi
	echo "download done!"
}

function get_start_script() {
	docker run -it --rm $DOCKER_IMG sed "s/^[^:]*: *//" /home/application/current/Procfile | tr -d "\r" | head -n1
}

function start(){
	if [ -z "$(docker images $DOCKER_IMG -q)" ] 
	then
		echo Image not found, downloading...
		download
	fi
	if [ "$COPY_ENV" == "1" ]
	then
		eval docker run -it --rm -u ubuntu -w /home/application/current -p 8888:$PORT $DOCKER_IMG /bin/bash -lc  \"source /home/ubuntu/.envs \&\& $(get_start_script)\"
	else
		eval docker run -it --rm -e PORT=8888 -e port=8888 -u ubuntu -w /home/application/current -p 8888:$PORT $DOCKER_IMG /bin/bash -lc \"$(get_start_script)\"
	fi
}

function update() {
	delete && start
}

function delete() {
	if [ -z "$(docker images $DOCKER_IMG -q)" ]
	then
		echo "Image not found"
	else
		docker rmi $DOCKER_IMG:latest --force
	fi
}

function main() {
	case "$1" in
	   update)
		  update
		  ;;
	   start)
		  start
		  ;;
	   delete)
		  delete
		  ;;
	esac
}

function help() {
	echo "Usage: tsuru $(basename $0) -a|--app <appname> [-p|--process <processname>] [-e|--copy-environment] [-P|--port <port|8888>]  [update | start | delete]"
}

export COPY_ENV=0
export PORT=8888
while [[ $# -ge 1 ]]
do
	key="$1"
	case $key in
		""|--help|-h)
			help
			exit 0
		;;
		-a|--app)
			export APP="$2"
			export DOCKER_IMG="$APP-tsuru"
			shift # past argument
		;;
		-p|--process)
			export PROCESSNAME="$2"
			shift # past argument
		;;
		-P|--port)
			export PORT="$2"
			shift # past argument
		;;
		-e|--copy-environment)
			export COPY_ENV=1
		;;
		update|start|delete)
			MODE="$1" 
		;;
		*)
			help
			exit 1
		;;
	esac
	shift # past argument or value
done

if [ "$APP" == "" ] || [ "$APP" == "" ]
then
	help
	exit 1
fi

main "$MODE"
